### ISSUE TITLE
custom comparator for custom path

### ISSUE THREAD

**Issue by alexkli** [adobe/sizewatcher#11]
Depends on #10.

Allow to quickly add a custom comparator for a file or folder in the config file.

```
comparators:
    custom:
      - name: my artifact
        path: build/artifact
      - path: build/artifact2
```

### Earlier notes

Could be reused by other checkers, or manually configured in `.sizewatcher` (but wait for some use cases for finding the right abstraction; e.g. maven dependencies aren't in a single folder).

- specify name
- specify directory to measure, with exclusions
