### ISSUE TITLE
absolute limits should be configurable per comparator

### ISSUE THREAD

**Issue by alexkli** [adobe/sizewatcher#20]
Global percentage based:
```
limits:
  fail: 40%
```

New - per comparator:
```
comparators:
  git:
    limits:
      fail: 10000
  node_modules:
    limits:
      fail: 5000
```

Still could be percentage or absolute byte value in each case.
