### ISSUE TITLE
support project structures where package.json is in subdirectory

### ISSUE THREAD

**Issue by alexkli** [adobe/sizewatcher#41]
Multiple considerations:

1. allow to run in subdirectory where package.json is located (or configure subdirectory) which currently conflicts with `Not inside the root of a git checkout` check
2. support multiple npm projects in a single git repo
3. how to best configure that with minimal effort (avoid forcing  to have a`.sizewatcher.yml`)

**Comment by alexkli** [comment]
The simplest (most naive) approach might be to configure it on the comparators:

```
comparators:
  node_modules:
    path: project-dir/
  npm_package:
    path: project-dir/
```

Since maybe we might have a mix of languages in different folders:

```
comparators:
  node_modules:
    path: nodejs-dir/
  maven:
    path: java-dir/
```

And `path` could also be an array to support multiple locations:

```
comparators:
  node_modules:
    path: ["folder/one", "folder/two"]
```
