### ISSUE TITLE
comparator for docker images

### ISSUE THREAD

**Issue by alexkli** [adobe/sizewatcher#45]
```
comparators:
  docker:
    - image: image/name # will look for first version found locally unless specified
      script: cd foo && docker build # to build the docker image
```
